### PR TITLE
use react-router-loader to cut down on boilerplate needed to load routes asynchronously

### PR DESCRIPTION
**Pull request by jedwards1211**
This is a good pattern to establish for loading routes asynchronously

### CODE REVIEW

**Comment by jordanh** [comment]
What's your rationale here? Why go from async to sync?

**Comment by jordanh** [comment]
Ah, nevermind – I see you're using the loader. It's a little less explicit. Are there other advantages?

**Comment by jedwards1211** [comment]
@jordanh not really, just prettier code, and I figured since I would want to be using this loader for my own new routes I might as well PR this pattern into the skeleton

**Comment by jedwards1211** [comment]
@jordanh ideally one would make something similar to `react-loader` that displays a loading component while fetching the chunk

**Comment by mattkrick** [comment]
That's an neat approach, but I'm hesitant to merge it because it's less expressive than what we've got. React-router has a predefined API for async routes. Making a synchronous API behave in an async fashion, IMHO, is a code smell because the async nature should be a property of the _function_, not the _location_. That reduced code comprehension will confuse the heck out of a noobie to the codebase who assumes `component` is synchronous.

**Comment by jedwards1211** [comment]
fair enough, well, I'll close this.  If you'd be interested in a similar approach that also provides loading banners while the chunks are being loaded, let me know, I've been thinking about making a fork of `react-router-loader` or `react-proxy-loader` that does that.

**Pull request closed without merging**
