### PR TITLE
prepend doctype on server render

### LINKED ISSUE #126: No way to set doctype - older browsers do not handle this well
Using Html.js to generate the initial HTML document, there is no way that I can find to insert a doctype. Older browsers really freak out about this.

First thought was to do something like the answer from this:
http://stackoverflow.com/questions/30626410/server-side-rendering-with-react-react-router-and-express
but not sure how to do that with streaming interface in createSSR.js and this didn't work:

```
const htmlStream = '<!DOCTYPE html>' + renderToStaticMarkup(<Html title="Meatier"
                                                store={store}
                                                assets={assets}
                                                renderProps={renderProps} />);
```

Looks like others have used handlebars to solve - but that seems like too much: https://github.com/jesstelford/react-isomorphic-boilerplate

### PR DESCRIPTION
**Pull request by wenzowski**
I'd prefer to avoid additional dependencies if possible.

Fixes #126 and closes #127.

### CODE REVIEW

**Comment by mattkrick** [comment]
@patrickleet can you confirm this works for your usecase?

**Comment by wenzowski** [comment]
@mattkrick perhaps @patrickleet should open a 2nd issue if it doesn't? This definitely prepends `<!DOCTYPE html>` to server-rendered html per 126

**Comment by mattkrick** [comment]
yep, although now that I think about it, couldn't we solve it by adding that line at the top of the doc here?https://github.com/mattkrick/meatier/blob/master/src/server/Html.js#L26

I have the luxury of supporting IE10+ so I don't have too much experience with this legacy stuff.

**Comment by wenzowski** [comment]
sadly

```diff
    return (
+     <!DOCTYPE html>
      <html>
```

produces a

```
    [Error] SyntaxError: ./src/server/Html.js: Unexpected token (26:7)
    at Parser.pp.raise (./node_modules/babylon/index.js:1378:13)
    at Parser.pp.unexpected (./node_modules/babylon/index.js:2817:8)
    at Parser.pp.jsxParseIdentifier (./node_modules/babylon/index.js:4115:10)
    at Parser.pp.jsxParseNamespacedName (./node_modules/babylon/index.js:4126:19)
    at Parser.pp.jsxParseElementName (./node_modules/babylon/index.js:4141:19)
    at Parser.pp.jsxParseOpeningElementAt (./node_modules/babylon/index.js:4218:20)
    at Parser.pp.jsxParseElementAt (./node_modules/babylon/index.js:4242:29)
    at Parser.pp.jsxParseElement (./node_modules/babylon/index.js:4291:15)
    at Parser.parseExprAtom (./node_modules/babylon/index.js:4303:21)
    at Parser.pp.parseExprSubscripts (./node_modules/babylon/index.js:504:19)
```

which I would imagine is why the react docs say to `'<!DOCTYPE html>' + renderToStaticMarkup()`

**Comment by mattkrick** [comment]
ahhh that's right, i think it's because `<!DOCTYPE html>` doesn't exist in JSX. I put in a feature request to `react-dom-stream` to see if he'll consider adding it in the package, but if not I'll accept this as soon as I get a response.

**Comment by wenzowski** [comment]
I saw all the stuff with through streams and assumed there was some problem writing to the pipe.
There isn't. Thanks for the sanity check @aickin

**Comment by patrickleet** [comment]
@mattkrick @wenzowski  yes this works - writing to res makes much more sense! thanks!

**Comment by mattkrick** [comment]
great! we'll accept for now with the hopes that it might get integrated into the streamer later.

**Pull request merged**
