### PR TITLE
Update graphql to 0.5.0, closes #130

### LINKED ISSUE #130: authToken should be passed to graphql via contextValue
from https://github.com/graphql/graphql-js/commit/d7cc6f9aed462588291bc821238650c98ad53580
> **[RFC] Add explicit context arg to graphql execution**
> This *BREAKING* change introduces a new argument to the GraphQL execution API which is presented to resolution functions: `context`.
> 
> This solves a long-standing point of confusion about the correct way to represent authentication or a "viewer context" in which a query is executed.
> 
> Previously, we suggested that the `rootValue` contain any authentication tokens, however this led to awkward code:
> 
> ```
> resolve: (val, args, { rootValue: { authToken } }) { ... }
> ```
> 
> Which can now be written as:
> 
> ```
> resolve: (val, args, authToken) { ... }
> ```
> 
> The `info` object is still created and provided to resolution functions, and the `rootValue` is still provided within it, however it is now the *fourth* argument rather than the *third*.

I've [built](https://github.com/wenzowski/graphql-js/archive/v0.4.19-alpha0.tar.gz) current [graphql/graphql-js#master](https://github.com/graphql/graphql-js/commit/39744381d5173795d3b245dcb5d86e78bb3638fe) to help get this integrated:
`https://github.com/wenzowski/graphql-js/archive/v0.4.19-alpha0.tar.gz`

Judging by [the new signature](https://github.com/graphql/graphql-js/blob/d7cc6f9aed462588291bc821238650c98ad53580/src/graphql.js#L43) this means separating the `authToken` from the other `rootVals` like so:

```diff
- const result = await graphql(Schema, query, {authToken, ...rootVals}, variables);
+ const result = await graphql(Schema, query, rootVals, authToken, variables);
```

and updating `resolve` functions like so:

```diff
- async resolve(source, args, {rootValue: {authToken}}) {
+ async resolve(source, args, authToken, {rootValue}) {
```

### PR DESCRIPTION
**Pull request by wenzowski**
next release of graphql has breaking changes
see https://github.com/graphql/graphql-js/commit/d7cc6f9aed462588291bc821238650c98ad53580

not ready for merge

### CODE REVIEW

**Comment by wenzowski** [comment]
app boots with these changes and appears to work on a quick perusal but the test suite fails on a rethinkdb call I don't have time to track down right now

**Comment by mattkrick** [comment]
nice! let's give it a couple days to hit npm, npm still doesn't treat github repos right (3 years and counting! https://github.com/npm/npm/issues/3081), also it doesn't allow for local caching, which kills if you're installing from a country with less-than-great internet.

**Comment by wenzowski** [comment]
yeah npm + git = :cry:
...thus the tarball :wink: 

graphql actually isn't usable directly from git anyway since @leebyron [changes the build dir](https://github.com/graphql/graphql-js/blob/master/resources/prepublish.sh#L24) in his prepublish hook

**Comment by mattkrick** [comment]
wowwww, if anyone wanted to compete with npm, now would definitely be the time for it. npm3 10x slowdown + left-pad + a book of unresolved issues...

**Comment by wenzowski** [comment]
definitely time for [gx](https://github.com/whyrusleeping/gx)

**Comment by mattkrick** [comment]
well, at least the name is better than ipfs :smile:. looks like it's getting a lil traction in JS land, too: https://github.com/ipmjs/gx-node

this could get interesting...

**Comment by wenzowski** [comment]
rebased and bumped graphql dep to latest

**Comment by mattkrick** [comment]
Looks good! Just 1 question... in the spec, the param for `authToken` is called `context`. Should `context` be an object that holds the `authToken`, or should it be the `authToken` itself, as it currently is? Basically, this: https://github.com/graphql/graphql-js/pull/326#issuecomment-200235854

I like how clean it is now, but the `context` will need to hold other things (for example, in the subscriptions the `socket` probably belongs in `context` instead of `refs.rootValue` since we're literally using the context of the socket & `rootValue` is more like the surrounding calculations). Thoughts?

**Comment by wenzowski** [comment]
Very good point. I'll look into that, and likely move the socket in too.

**Pull request merged**
