### PR TITLE
add optional BASENAME environment variable to mount app at non-root path

### PR DESCRIPTION
**Pull request by jedwards1211**
so for example by doing `BASENAME=/portal npm start` the app is mounted at `localhost:3000/portal` instead of root.

For prod, `BASENAME` has to be defined both while building and when launching: `BASENAME=/portal npm run build && npm run prod`

### CODE REVIEW

**Comment by mattkrick** [comment]
oh boy, i really appreciate the recent PRs! Unfortunately, I can't accept this & want to ***actively discourage you from doing this with all my heart & soul.*** Here's why:

The JWT is kept in `localStorage`, which is shared with everything within that domain (it follows the same-origin policy). That means, on some page sharing that same domain there could be a single line of code that does something like `sendToAttacker(localStorage.getItem('authToken'))`. Even if the owner of that other page can be trusted, their code can't. They could be susceptible to XSS, CSRF, etc. attacks. In short, if it's not in the SPA, it can't be trusted, and we shouldn't share our secrets with something that can't be trusted. 

Instead, if you're at `foo.com/meatier` I'd instead create a separate domain like `meatier.foo.com`, which might cause you CORS headaches, but will be safe.

**Comment by jedwards1211** [comment]
Okay, I didn't have a deep understanding of that.  Thanks for warning me!

**Comment by jedwards1211** [comment]
So the whole reason I was using a basename is to avoid shelling out extra $ for a wildcard certificate for the web services I'm making for my small caving club.  I'm the only developer working on our website.  Do you have any advice for this situation?  I think using a basename is probably worth it in this case.

**Comment by mattkrick** [comment]
$5 droplet + dokku + lets encrypt will be more than sufficient

**Comment by jedwards1211** [comment]
Cool, I hadn't heard of let's encrypt.  As far as dokku though, I'm looking for something that supports docker-compose

**Pull request closed without merging**
