### PR TITLE
pass server values of PROTOCOL, HOST, and PORT to client at runtime

### PR DESCRIPTION
**Pull request by jedwards1211**
Fixes https://github.com/mattkrick/meatier/issues/164.

How it works:

* SSR injects this script at the top of the body with values from server's `process.env` (see `clientEnv.js`):
```html
<script>window.__env__ = {PROTOCOL: ..., HOST: ..., PORT: ...}</script>
```
* `client/process.js` gets the `process` polyfill that webpack normally uses and adds the environment variables from `window.__env__` to it
* Webpack configs use `ProvidePlugin` to replace all references to `process` on the client side with (esentially) `require('client/process.js')`
* Note: I put `client/process.js` in the commons chunk since some of the vendor deps refer to `process`.

#### TODO
* [ ] double check that this doesn't stomp on `process.env.NODE_ENV` defines.

### CODE REVIEW

**Comment by jedwards1211** [comment]
Btw, I added basename support to my own project.  Once this gets merged, I can make a PR for (optional) basename support.

**Comment by mattkrick** [comment]
possibly naive question: why wouldn't this work in your `hostUrl` equivalent?

```
if (typeof window !== 'undefined') {
    return window && window.location && window.location.host || 'localhost:3000';
}
return 'localhost:3000';
```

**Comment by jedwards1211** [comment]
@mattkrick it's true, that's probably better as far as getting the host URL.  I think this PR is a good paradigm for passing other envionment variables to the client that are unrelated to the host URL though.

**Comment by jedwards1211** [comment]
Also, `hostUrl` is currently used on both client and server

**Comment by mattkrick** [comment]
It is a really fascinating pattern! I guess I'm just at a loss on what variables you would need to pass in at runtime that your server defines at compile time. If you come up with an example I'll be happy to reassess, but for now I've got 3 concerns with this PR:

1. it defies the KISS principle: the browser knows what it's connected to & how it's connected. It doesn't need the server to send it something to tell it that.

2. The code doesn't express intent. Looking at the entire codebase, it'd be _really_ hard to decipher what these changes are doing & how they work together. This makes it harder to maintain. To improve, make a `hostUrl` factory that takes in `window.__env__` & exports the result. That keeps us away from doing process mocking and making that mock a global (because ProviderPlugin is basically just a globalfier).

3. It's taking something that was done in compile time & moving it into runtime, which is the opposite of the direction we wanna go. Like they always say, "don't put off till runtime what you can do in compile time". :smile:

**Comment by jedwards1211** [comment]
Fair enough.  I was wrong, I was only using `hostUrl` on the server in my project.  In my upcoming PR for basename support I'll change `hostUrl` to use `window.location.origin` like you suggested.

**Pull request closed without merging**
