### PR TITLE
react-toolbox conversion

### PR DESCRIPTION
**Pull request by Bartekus**
Everything works in development but not in production due to createSSR.js needing some TLC... TBC

### CODE REVIEW

**Comment by mattkrick** [comment]
awesome!! i'll dig into making it work in production, in the next couple days

**Comment by renato** [comment]
Oh crap, we did almost the same work (even the `color: #000`), hehehe. https://github.com/renato/meatier/commit/b6004b1bde79543fb03581f4c4b658d82a0e7394

Just one thing, shouldn't the RaisedButton become Button raised={true}?

**Comment by Bartekus** [comment]
I've incorporated your work into it as to streamline the process. There are few things that still need to be taken care so having pull open allows others to see and contribute to the process as well. At the moment production is not completing resulting in response timeout so I'm looking into SSR file being the mostlikely culprit atm. But it's not definite, I'll have more time in the evening to better trace the process and figure where it hangs.

**Comment by Bartekus** [comment]
At this point I'm very certain that everything executes:
```
export default async function createSSR(req, res) {
  const finalCreateStore = applyMiddleware(thunkMiddleware)(createStore);
  const store = finalCreateStore(makeReducer(), iMap());
  if (process.env.NODE_ENV === 'production') {
```
until this line:
```
const makeRoutes = require('../../build/prerender');
```
That being said, Html also isn't happening as none of the render() function is currently executing.

**Comment by mattkrick** [comment]
style-loader is the one throwing the window error. i'm wondering if we could build the react-toolbox into css before server it, that'll keep build times to a minimum and obviate the need for sass deps within our webpack config

**Comment by mattkrick** [comment]
cleaning up PRs, still got a version of this as a branch if you wanna check it out. Basically I think react-toolbox has a little more tightening up to do before it becomes a good replacement

**Pull request closed without merging**
