### PR TITLE
azk.io-integration

### PR DESCRIPTION
**Pull request by Bartekus**
Scope of Work:
- Azk.io Integration

Objective Status:
- Successful

Changelog
- 0.10
 - Added Azk.io orchestrate development environments
  - Resolved issue #67 : How to deploy in production?
  - Resolved issue #64 : Make meatier more configurable for deployment

Memo:
- Everything has been tested and confirmed operational in and out of azk.io environment.
- Full deployment capability has been achieved

### CODE REVIEW

**Comment by lndb** [comment]
Please if possible keep the Azk.io Integration in a different branch, and the master branch for the meatier without Azk.io

**Comment by Bartekus** [comment]
@lndb Any particular reason for that request? By going with azk.io we're moving with where the technology is going. Dockerizing is a way to unify development and deployment environment across multitude of systems. The goal is to minimize artifacts and allow teams to focus on development of their software and not troubleshooting their dev environments or deployment servers.

**Comment by patrickleet** [comment]
@lndb @Bartekus - The changes from my PR here: https://github.com/mattkrick/meatier/pull/64, aimed to keep azk.io separate. You can run with npm run quickstart, as usual, or just azk start. Having an Azkfile.js in your project should be an optional file that you can choose to use or not, IMO.

Unfortunately, there are a lot of places where azk is hardcoded in this PR. ( src/server/database/rethink.config.js) and (src/universal/modules/admin/components/Graphql/Graphql.js) and (src/universal/utils/fetching.js) where these should just be environment variables exported by the Azkfile.js.

**Comment by Bartekus** [comment]
@patrickleet I understand, the reason for azk.io emphasis is to make development studios life easier, by having unified development environment a lot of issues are averted. However since you are right that it should be optional, we sifted the insistence on it's adoption to r3stack, since that will aim to provide everything meatier does but in easily reproducible and deployable environment. After all azk is just docker, albite with more readable and understandable documentation and one central configuration file for whole orchestration. I'm going to try implement all the changes that you have thus far made but I also have to make sure that they won't disrupt azk.io since we need it to work in that environment. And if it will work there, then it work for everybody else that ever uses it so in a way, we're resolving a lot of headaches by focusing on it in the long run.

If you are interested in ideology of Aaron Swartz and would like to join our round table hacking organization called Araphel, and by the extension r3stack project, please feel free to email me: bartekus ~at~ gmail ~dot~ com

**Comment by mattkrick** [comment]
Cleaning up PRs & leaving this one since it seems like there's still some flexibility work that azk needs to tackle before it's good nuff for meatier

**Pull request closed without merging**
