### PR TITLE
minor changes (Uppercase Naming) to make it work on Linux

### PR DESCRIPTION
**Pull request by Valentin-Seehausen**
Just renamed
/src/universal/components/lostPassword -> /src/universal/components/LostPassword
/src/universal/components/lostPassword/lostPassword.css -> /src/universal/components/LostPassword/LostPassword.css
/src/universal/components/lostPassword/lostPassword.js -> /src/universal/components/LostPassword/LostPassword.js

I had problems running on Linux, webpack gave me some kind of error that it was unable to load modules. It seems like OSX loads the modules anyway, but on Linux (Mint 17, based on Ubuntu 14.04) I had to rename the files / directories.

### CODE REVIEW

**Comment by mattkrick** [comment]
you figured it out, nice!
that kinda makes sense, Mint creates a case-sensitive file system whereas OSX isn't case-sensitive by default. Still, JavaScript is case sensitive, so I'm not sure why it threw....
the PR has some unneeded stuff, so i just changed it.

**Comment by Valentin-Seehausen** [comment]
Great! Happy end :)

Can you tell me, what I did "wrong" with the PR? It was my first one.

**Comment by mattkrick** [comment]
Sure, if you check out the files changed, you'll see that 5 files changed when you only wanted to change 2 of them. I think the `:ostPassword` is from an old commit, so I'm guessing you did a `git pull` and then accepted your version over the newer version? Also, the `stdout.txt` wasn't necessary to commit.

**Comment by Valentin-Seehausen** [comment]
Ah ok, perfect. Thank you. Better next time.

**Pull request closed without merging**
