### PR TITLE
Update Google Oauth

### PR DESCRIPTION
**Pull request by trungtin**
It's nothing, just moving some of your code from `universal` to `server`, please see the diff.
I don't think your old ways should work if browser not logged in to Google before using oauth, am I right? This trying to open a new tab for user to login Google.
PS: Thanks for this wonderful repos :+1:

### CODE REVIEW

**Comment by mattkrick** [comment]
Would you mind doing a pull against the latest version? Looks like the PR is based off an old version and would undo the changes made from the couple past commits

**Comment by trungtin** [comment]
sorry, my bad, somehow screwed up when rebase. I force updated my branch, is it enough or I must make an other pull request?

**Comment by mattkrick** [comment]
Whoa, you're sending a script in a payload? That's really, really dangerous and opens the site up to xss attacks. Sorry, as is I can't accept. Wouldn't it be possible to change the cors headers to accomplish this?

**Comment by trungtin** [comment]
Yes I knew it's ugly and dangerous, but we're only talking about some big site like Google and Facebook, right, what could go wrong? What the different from sending payload then write to localStorage vs sending a script writing that same payload to localStorage. I don't know, maybe there is other way. But the only way I knew to communicate between tab is using localStorage. Let's me take a peek at how Google implement their JS oauth client.

**Comment by mattkrick** [comment]
I'll leave this open and try to reproduce. It just requires a browser that's not logged into google, right?

The problem is designing a client that accepts dangerous script tags. That means someone could use that redux action to trigger any rogue code, and since we're talking about a JWT, then they could steal user info with relative ease. From a security standpoint, you never want any client code designed to eval a script, trusting google isn't good enough.

**Comment by mattkrick** [comment]
closing PR, leaving issue open for a safer solution

**Pull request closed without merging**
