### PR TITLE
Upgrade all the things

### PR DESCRIPTION
**Pull request by wmertens**
thanks to npm-check-updates. I excluded things I wasn't sure about. Tests pass and everything seems to work.

### CODE REVIEW

**Comment by wmertens** [comment]
oops the new XO adds a lot of rules that fail now. I suppose that means updating `eslint-config-xo-meatier`?

**Comment by lndb** [comment]
@wmertens can you please also upgrade the rest of the packages?

**Comment by mattkrick** [comment]
upgrading all the stuff would be a major undertaking. things like redux-form, react-router, etc. have all gone through huge API revisions. For an up-to-date starter template, use https://github.com/parabolinc/action and remove the modules folder & the graphql models.

**Comment by wmertens** [comment]
Going to close this one, never did fully complete it and ended up going in a different direction.

**Pull request closed without merging**
