### PR TITLE
surface graphql errors

### PR DESCRIPTION
**Pull request by wenzowski**
In the interest of getting progress on #103, and to establish a pattern for future tests, this gives us stack traces when graphql spits back errors.

### CODE REVIEW

**Comment by mattkrick** [comment]
this looks good, but AVA still hasn't published the latest version on npm so I'll sit on this until we get the AVA version bump.

**Comment by wenzowski** [comment]
Sure, though this makes a bunch of other tests fail in addition to one referenced by above issue: the graphql errors surfaced here appear to be independent from ava update. Note that to produce errors the db must be reset immediately before running test suite; all subsequent runs pass.

**Comment by mattkrick** [comment]
any idea why that is? that stumped me when i first saw it, but i haven't taken the time to investigate further...

**Comment by wenzowski** [comment]
no clue...yet

**Comment by wenzowski** [comment]
We could probably work around the upstream error by passing a resolve function to graphql:

```javascript
function correctedResolveFn(source, args, { fieldName }) {
  // ensure source is a value for which property access is acceptable.
  if (typeof source !== 'number' && typeof source !== 'string' && source) {
    const property = (source: any)[fieldName];
    return typeof property === 'function' ? property(source) : property;
  }
}
```

**Comment by wenzowski** [comment]
Proper fix being tracked in graphql/graphql-js#332

**Comment by wenzowski** [comment]
completion of this pr requires unreleased graphql; blocking on #130

**Comment by wenzowski** [comment]
:point_up_2: and by "completion" I mean getting the tests to pass.
This could still be merged as-is since it's just adding detail to already failing tests.

**Comment by wenzowski** [comment]
This is now just waiting on `ava` per #123 and linting.

**Comment by wenzowski** [comment]
rebased and green

**Pull request merged**
